import { useEffect, useRef, useState } from 'react'
import type { Bundle } from './main'
type Status={key_configured:boolean;available:boolean;model:string;estimated_usd:number;calls:number;limit_usd:number;input_tokens:number;output_tokens:number;cached_tokens:number;cache_write_tokens:number;note:string}
type Answer={status:string;reason?:string;message?:string;cached?:boolean;seconds?:number;proposal?:Bundle;metrics?:{metric_id:string;label:string;value:number;unit:string;source:string}[];evidence?:{evidence_id:string;text:string}[];tool_trace?:{tool:string;plan_id:string}[]}
async function request<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await response.json();if(!response.ok)throw new Error(data.error||'Не удалось выполнить запрос');return data}
const prompts=['Сократи бюджет на 30%, исключи звонки и оставь не больше пяти кампаний','Почему выбран этот канал, а не звонок?','Какие кампании сильнее зависят от непроверенных предположений?']
const toolNames:Record<string,string>={get_plan_summary:'Показатели плана',get_campaign_evidence:'Основания кампании',propose_scenario:'Пересчёт движком',compare_plans:'Сравнение версий'}
export function AssistantPanel({runId,original,active,selected,onClose,onProposal,initialPrompt}:{initialPrompt?:string;runId:string;original:Bundle;active:Bundle;selected:number;onClose:()=>void;onProposal:(value:Bundle)=>void}){
  const [status,setStatus]=useState<Status|null>(null),[text,setText]=useState(initialPrompt||''),[answer,setAnswer]=useState<Answer|null>(null),[working,setWorking]=useState(false),[base,setBase]=useState(active.plan_id),[error,setError]=useState('')
  const keyInput=useRef<HTMLInputElement>(null),[configuring,setConfiguring]=useState(false),[configuredNotice,setConfiguredNotice]=useState('')
  const job=useRef(''),token=useRef(0),input=useRef<HTMLTextAreaElement>(null),panel=useRef<HTMLElement>(null)
  useEffect(()=>{void request<Status>('/api/assistant/status').then(setStatus).catch(()=>setError('Не удалось проверить доступность ассистента'));input.current?.focus();return()=>{token.current++;if(job.current)void request(`/api/assistant/jobs/${job.current}/cancel`,{}).catch(()=>{})}},[])
  async function connect(){setConfiguring(true);setError('');setConfiguredNotice('');const key=keyInput.current?.value||'';if(keyInput.current)keyInput.current.value='';try{const result=await request<{status:Status}>('/api/assistant/configure',{api_key:key});setStatus(result.status);setConfiguredNotice('Ключ сохранён на этом компьютере. GPT-5.4 mini подключена к приложению; отправьте запрос, чтобы проверить доступ к API.')}catch(e){setError(String(e).replace('Error: ',''))}finally{setConfiguring(false)}}
  async function cancel(){token.current++;if(job.current)await request(`/api/assistant/jobs/${job.current}/cancel`,{}).catch(()=>{});job.current='';setWorking(false);setAnswer({status:'cancelled',message:'Запрос отменён. Активный план не изменён.'})}
  async function ask(){const current=++token.current;setWorking(true);setAnswer(null);setError('');try{const started=await request<{job_id:string}>('/api/assistant',{run_id:runId,base_plan_id:base,prompt:text,campaign_index:selected});job.current=started.job_id
    for(let i=0;i<100;i++){await new Promise(resolve=>setTimeout(resolve,500));if(current!==token.current)return;const response=await request<{status:string;result?:Answer}>(`/api/assistant/jobs/${job.current}`);if(response.status==='completed'){setAnswer(response.result||null);job.current='';return}}
    await cancel();setError('Время ожидания истекло. План не изменён.')
  }catch(e){setError(String(e).replace('Error: ',''))}finally{if(current===token.current){setWorking(false);void request<Status>('/api/assistant/status').then(setStatus).catch(()=>{})}}}
  function keydown(event:React.KeyboardEvent){if(event.key==='Escape'){onClose();return}if(event.key==='Tab'){const nodes=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input, textarea, select, summary');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}
  return <div className="assistant-overlay"><button className="drawer-backdrop" aria-label="Закрыть ассистента" onClick={onClose}/><aside className="assistant-drawer" role="dialog" aria-modal="true" aria-labelledby="assistant-title" ref={panel} onKeyDown={keydown}><div className="assistant-header"><div><span className="eyebrow">BEEAGENT</span><h2 id="assistant-title">Разбор плана</h2></div><button className="close-drawer" onClick={onClose} aria-label="Закрыть">×</button></div><div className="assistant-body"><p className="assistant-intro">Меняйте условия словами и разбирайте решения. Числа рассчитывает движок, а новый вариант ждёт вашего подтверждения.</p>
    {status&&!status.available&&<div className="ai-offline" role="status"><strong>AI-ассистент временно недоступен</strong><p>Изменить условия можно вручную. Серверный доступ настраивается локально.</p></div>}
    <details className="ai-connect" open={!status?.key_configured}><summary>{status?.key_configured?'Настройка подключения':'Подключить OpenAI'}</summary><p>Модель GPT-5.4 mini. Вставьте новый ключ сюда, без терминала. Он хранится только в локальном файле настроек на этом компьютере, не отправляется в Git и не отображается в ответах.</p><form onSubmit={e=>{e.preventDefault();void connect()}}><label className="field" htmlFor="local-api-key">OpenAI API-ключ<input ref={keyInput} id="local-api-key" type="password" autoComplete="off" spellCheck={false} placeholder="Вставьте ключ" maxLength={503} required disabled={configuring||working}/></label><button type="submit" className="secondary full" disabled={configuring||working}>{configuring?'Сохраняем…':'Сохранить ключ локально'}</button></form><p>Сохранение бесплатно. Запросы ассистенту расходуют API-баланс; предел локальной оценки расходов по умолчанию $3. Проверка доступа выполняется при отправке запроса.</p></details>{configuredNotice&&<div className="message notice" role="status">{configuredNotice}</div>}
    <label className="field">Базовый план<select value={base} onChange={e=>{setBase(e.target.value);setAnswer(null)}} disabled={working}><option value={original.plan_id}>Исходный план</option>{active.plan_id!==original.plan_id&&<option value={active.plan_id}>Активный вариант</option>}</select></label><p className="base-note">Процент изменения бюджета считается от лимита выбранной версии. Для вопросов о канале выбрана кампания {selected+1}.</p>
    <div className="prompt-suggestions">{prompts.map(p=><button key={p} disabled={working} onClick={()=>{setText(p);input.current?.focus()}}>{p}</button>)}</div><form onSubmit={e=>{e.preventDefault();void ask()}}><label className="field" htmlFor="assistant-prompt">Ваш запрос</label><textarea ref={input} id="assistant-prompt" value={text} onChange={e=>setText(e.target.value)} maxLength={2000} rows={4} placeholder="Например, сократи бюджет на 30%" disabled={working}/><div className="assistant-form-footer"><span>{text.length} / 2000</span>{working?<button type="button" className="secondary" onClick={()=>void cancel()}>Отменить</button>:<button className="primary" disabled={!text.trim()} type="submit">Отправить запрос</button>}</div></form>
    {working&&<div className="message loading" role="status"><span className="spinner"/>Ассистент проверяет данные плана…</div>}{error&&<div className="message error" role="alert">{error}</div>}
    {answer&&<div className="assistant-answer" aria-live="polite">{answer.message&&<p>{answer.message}</p>}{answer.status==='completed'&&<><div className="answer-source">{answer.cached?'Сохранённый ответ для этой версии':'Ответ на основании расчётов'} · {answer.seconds?.toFixed(1)} с</div><div className="assistant-metrics">{answer.metrics?.map(m=><div key={m.metric_id}><span>{m.label}</span><strong>{new Intl.NumberFormat('ru-RU',{maximumFractionDigits:m.unit==='%'?1:0}).format(m.value)} <small>{m.unit}</small></strong><small>{m.source}</small></div>)}</div>{answer.evidence?.map(e=><p className="grounded-evidence" key={e.evidence_id}>{e.text}</p>)}{answer.proposal&&<button className="primary full" onClick={()=>onProposal(answer.proposal!)}>Сравнить</button>}<details><summary>Что сделал агент</summary>{answer.tool_trace?.map((t,i)=><p key={i}>{toolNames[t.tool]||'Расчёт'} · версия {t.plan_id.slice(0,8)}</p>)}<p>Числа и пояснения получены из серверных расчётов. Ассистент выбирает ссылки на них, не создаёт новые значения.</p></details></>}</div>}
    {status&&<details className="ai-usage"><summary>Настройки и расход AI</summary><p>Модель: {status.model}</p><p>Вызовы: {status.calls}. Оценка расходов: ${status.estimated_usd.toFixed(4)} из ${status.limit_usd.toFixed(2)}.</p><p>Входные токены: {status.input_tokens}; выходные: {status.output_tokens}; из кеша: {status.cached_tokens}; записано в кеш: {status.cache_write_tokens}.</p><p>{status.note}</p></details>}
  </div></aside></div>
}
