import type { Bundle, Pilot, Audit } from './main'
import { Tariff, tariffName, pilotConsequence, channelLabel as channel } from './presentation'
const n=(x:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(x)
const pct=(x:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(x*100)+'%'
export function PilotImpact({pilots,all=false}:{pilots:Pilot[];all?:boolean}){
  const ranked=pilots.filter(p=>p.decision_change).sort((a,b)=>Math.abs(b.decision_change!.estimate_channel_after-b.decision_change!.estimate_channel_before)-Math.abs(a.decision_change!.estimate_channel_after-a.decision_change!.estimate_channel_before))
  const repeat=ranked.find(p=>p.repeat_validation)
  const changes=all?pilots:repeat?[...ranked.filter(p=>p!==repeat).slice(0,2),repeat]:ranked.slice(0,3)
  return <><h2>{all?'История исследования':'Как пилоты изменили решения'}</h2><p>Сохранённые наблюдения исходного исследования. Изменение условий не запускает новые пилоты.</p>{!changes.length?<p>В этом архивном запуске изменения плана не записаны.</p>:<div className="pilot-impact">{changes.map(p=>{const d=p.decision_change;return <article key={p.index}><div className="impact-title"><h3>Пилот {p.index} {p.repeat_validation&&<span className="repeat-label">Повторная проверка крупного решения</span>}</h3><span>Канал: {channel[p.campaign.channel]} · {n(p.actual_n)} контактов</span></div><div className="tariff-pair"><div><span className="field-caption">Текущий тариф</span><Tariff code={p.campaign.filter_current_tariff}/></div><div><span className="field-caption">Предложение</span><Tariff code={p.campaign.target_tariff}/></div></div><div className="impact-values"><span>Ожидали <b>{d?pct(d.estimate_channel_before):'Нет записи'}</b></span><span>Получили в пилоте <b>{pct(p.observed_ratio)}</b></span><span>Обновили оценку <b>{d?pct(d.estimate_channel_after):'Нет записи'}</b></span></div><p className="consequence">{pilotConsequence(p)}</p><details><summary>Основания и планы до и после</summary><p>Запрошено {p.requested_n}, выполнено {p.actual_n} контактов. Расход {n(p.cost)} у.е.</p><p>{p.reason}</p>{d&&<div className="decision-pair">{[['До наблюдения',d.before],['После наблюдения',d.after]].map(([label,value])=>{const v=value as typeof d.before;return <div key={String(label)}><strong>{String(label)}</strong><ol>{v.plan.map((c,i)=><li key={i}>Текущий: {c.filter_current_tariff?.split(';').map(tariffName).join(', ')||'Все тарифы'}. Предложение: {tariffName(c.target_tariff)} · {channel[c.channel]}</li>)}</ol><small>Прогноз плана: {n(v.forecast_net)} у.е.</small></div>})}</div>}<p>Сопоставлены направление, сегмент и группа каналов: SMS, Push и реклама используют общую оценку. Позиция отражает порядок исполнения, а не вероятность успеха. Прогноз учитывает расход пилота; это не измеренная выгода.</p></details></article>})}</div>}</>
}
export function ForecastQuality({active}:{active:Bundle}){
  const measured=active.measurement?.net_arpu_gain
  return <><span className="eyebrow">КАЧЕСТВО ПРОГНОЗА</span><h2>{measured==null?(active.archived?'Архивные данные':'Ещё не проверен на данных кейса'):'Прогноз и результат расходятся'}</h2>{measured!=null?<div className="calibration-gap"><span>Прогноз минус результат проверки</span><strong>{n(active.forecast.net-measured)} у.е.</strong><p>Обе величины, чистый прирост с учётом пилотов и расходов. Прогноз не откалиброван.</p></div>:<p>{active.archived?'Сохранённые результаты относятся к прежнему движку или данным. Новый расчёт нужен для продолжения работы.':'У этой версии нет соответствующего измерения. Числа исходного плана не перенесены на новый вариант.'}</p>}<details><summary>Разобрать расхождение</summary><p>Шумные положительные оценки чаще выигрывают отбор. Перенос истории на другую аудиторию и большая ожидаемая выручка усиливают денежную ошибку. Повторная проверка снижает часть неопределённости, но не гарантирует точность.</p><p>Уникальный охват с пилотами оценён вероятностно: идентификаторы выбранных для пилота клиентов недоступны.</p><p>Данные синтетические. Это не доход реального Beeline и не прогноз скрытого судейства.</p></details></>
}
export function GroupedFindings({audit}:{audit:Audit}){
  const categories=[['Допустимость плана',(code:string,severity:string)=>severity==='error'],['Качество данных',(code:string,severity:string)=>severity!=='error'&&code==='unpiloted'],['Статистическая неопределённость',(code:string,severity:string)=>severity!=='error'&&code==='uncertain_sign'],['Исполнение и ресурсы',(code:string,severity:string)=>severity!=='error'&&!['unpiloted','uncertain_sign'].includes(code)]] as const
  const labels:Record<string,string>={overlap:'Повторные контакты',truncation:'Усечение аудитории',requested_resources:'Полная аудитория не помещается в лимиты',unpiloted:'Есть направления без пилотных наблюдений',uncertain_sign:'Интервал оценки включает ноль',empty:'Пустая фактическая аудитория',invalid_campaign:'Некорректные правила',disabled_channel:'Отключённый канал',campaign_count:'Недопустимое число кампаний'}
  return <div className="grouped-findings">{categories.map(([label,accept])=>{const findings=audit.findings.filter(f=>accept(f.code,f.severity));if(!findings.length)return null;return <section key={label}><h3>{label}</h3>{[...new Set(findings.map(f=>f.code))].map(code=>{const group=findings.filter(f=>f.code===code);return <details key={code}><summary>{labels[code]||group[0].message} <span>· {group.length}</span></summary><p>Относится к: {[...new Set(group.map(f=>f.index==null?'всему плану':`кампании ${f.index+1}`))].join(', ')}.</p>{code==='invalid_campaign'&&[...new Set(group.map(f=>f.message))].map(m=><p key={m}>{m}</p>)}</details>})}</section>})}</div>
}
