import React, { useEffect, useState, useRef } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'
import { AssistantPanel } from './AssistantPanel'
import { ScenarioComparison } from './ScenarioComparison'

type Campaign = {campaign_name?:string;target_tariff:string;channel:string;filter_current_tariff?:string;filter_arpu_segment?:string;filter_data_segment?:string;filter_call_segment?:string}
type Detail = {campaign:Campaign;audience:number;contacts:number;cost:number;marginal_net:number;uncertainty_scale:number;final_overlap:number;truncated:boolean;campaign_capped:boolean}
type Forecast = {source:string;net:number;gross:number;cost:number;contacts:number;final_unique:number;estimated_unique:number;details:Detail[];constraints:Constraints}
type Constraints = {budget:number;channels:string[];max_campaigns:number;contacts?:number;risk?:number}
type Finding = {code:string;severity:string;message:string;index?:number}
type Audit = {valid:boolean;findings:Finding[];forecast:Forecast}
type Evidence = {cell:string;channel_mean:number;sd:number;interval:number[];samples:number;pilots:number;prior:{n_history:number;historical_change:number;adoption_heuristic:number}}
type Passport = {index:number;status:string;pilots:number[];evidence:Evidence[];best_rejected_alternative:null|{target:string;channel:string;plan_net:number};rejection_reason:string;could_change:string}
type Pilot = {index:number;cell:string;campaign:Campaign;actual_n:number;requested_n:number;cost:number;observed_ratio:number;prior:{mean:number};posterior:{mean:number};reason:string}
type Official = {net_arpu_gain:number;total_cost:number;total_contacts:number;unique_customers_targeted:number;n_pilots:number;status:string}
export type Bundle = {plan_id:string;run_id:string;data_version:string;base_plan_id?:string;measurement?:Official|null;plan:Campaign[];forecast:Forecast;audit:Audit;passports:Passport[];cautious_net:number;source:string;new_pilots?:number;delta?:Record<string,number>;before_audit?:Audit}
type Run = Bundle & {active_bundle?:Bundle;run_id:string;seed:number;seconds:number;created_at:string;official:Official;pilots:Pilot[];knowledge_summary:{snapshot_id:string;stop_reason:string;spent_budget:number;spent_contacts:number;diagnostics:{excluded_missing_or_invalid:number;profile_rows:number};assumptions:string[]}}
type RunSummary = Pick<Run,'run_id'|'seed'|'seconds'|'created_at'|'official'|'source'>
type Comparison = {source:string;policies:{policy:string;summary:{mean_net:number;median_net:number;min_net:number;max_net:number;positive_runs:number;mean_seconds:number};results:{seed:number;net_arpu_gain:number}[]}[]}

const n = (x:number|undefined, digits=0) => x == null ? 'Нет оценки' : new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits}).format(x)
const pct = (x:number) => `${n(x*100,1)}%`
const signed = (x:number) => `${x>0?'+':''}${n(x)}`
const tariff = (s:string|undefined) => (s||'Все тарифы').replaceAll('tariff_','T').replaceAll(';',', ')
const segment=(s:string|undefined)=>({LOW:'Низкая выручка',MID:'Средняя выручка',HIGH:'Высокая выручка',HEAVY:'Активный интернет',LITE:'Умеренный интернет',NON_USER:'Без интернета',MEDIUM:'Умеренные звонки'}[s||'']||s||'Все сегменты')
const channels = ['push','sms','digital_ads','call']
const channelLabel:Record<string,string> = {push:'Push',sms:'SMS',digital_ads:'Реклама',call:'Звонки'}
const policyLabel:Record<string,string> = {template:'Шаблон организаторов',history_only:'На основе истории',fixed_pilots:'С фиксированным планом проверок',adaptive:'С учётом результатов проверок'}
async function api<T>(url:string, body?:unknown):Promise<T>{
  const response = await fetch(url,body === undefined ? undefined : {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
  const data = await response.json()
  if(!response.ok) throw new Error(data.error || `Ошибка ${response.status}`)
  return data as T
}
function Icon({name}:{name:string}) {const paths:Record<string,React.ReactNode>={plan:<><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></>,pilot:<><path d="M9 3h6M10 3v6L4 19q-1 2 2 2h12q3 0 2-2L14 9V3M8 14h8"/></>,compare:<><path d="M5 20V10M12 20V4M19 20V13"/></>,audit:<><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/></>,arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,download:<><path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{paths[name]||paths.plan}</svg>}
function App(){
  const [runs,setRuns]=useState<RunSummary[]>([]),[run,setRun]=useState<Run|null>(null),[scenario,setScenario]=useState<Bundle|null>(null)
  const [tab,setTab]=useState('overview'),[selected,setSelected]=useState(0),[seed,setSeed]=useState(42),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const [constraints,setConstraints]=useState<Constraints>({budget:100000,channels:[...channels],max_campaigns:10})
  const [draft,setDraft]=useState(''),[audit,setAudit]=useState<Audit|null>(null),[comparison,setComparison]=useState<Comparison|null>(null)
  const [proposal,setProposal]=useState<Bundle|null>(null),[assistantOpen,setAssistantOpen]=useState(false),[launchOpen,setLaunchOpen]=useState(false)
  const polling=useRef(0)
  const active=scenario||run, passport=active?.passports[selected]
  async function refresh(){setRuns(await api<RunSummary[]>('/api/runs'))}
  async function open(id:string){setBusy('Открываем сохранённый запуск…');setError('');try{const r=await api<Run>(`/api/runs/${id}`);setRun(r);setScenario(r.active_bundle?.plan_id!==r.plan_id?r.active_bundle||null:null);setProposal(null);setAudit(null);setSelected(0);setSeed(r.seed);setConstraints({...((r.active_bundle||r).forecast.constraints)});setDraft(JSON.stringify((r.active_bundle||r).plan,null,2))}catch(e){setError(String(e))}finally{setBusy('')}}
  useEffect(()=>{api<RunSummary[]>('/api/runs').then(list=>{setRuns(list);if(list[0])void open(list[0].run_id)}).catch(e=>setError(String(e)));api<Comparison>('/api/benchmarks').then(setComparison).catch(()=>{})},[])
  async function research(){setLaunchOpen(false);const token=++polling.current;setBusy('Проверяем гипотезы и рассчитываем план…');setError('');setNotice('');try{
    const job=await api<{run_id:string}>('/api/runs',{seed});let completed=false
    for(let attempt=0;attempt<300;attempt++){await new Promise(r=>setTimeout(r,800));if(token!==polling.current)return;const status=await api<{status:string;error?:string}>(`/api/runs/${job.run_id}`);if(status.status==='failed')throw new Error(status.error);if(status.status==='completed'){completed=true;break}}
    if(!completed)throw new Error('Исследование ещё выполняется. Откройте запуск позднее.')
    await refresh();await open(job.run_id);setNotice('Исследование завершено. Показаны сохранённые результаты реального запуска.');setTab('overview')
  }catch(e){setError(String(e))}finally{setBusy('')}}
  function parsedPlan(){try{const value:unknown=JSON.parse(draft);if(!Array.isArray(value))throw new Error();return value}catch{throw new Error('Не удалось прочитать правила. Ожидается список кампаний в формате JSON.')}}
  async function replan(repair=false){if(!run)return;setBusy(repair?'Исправляем план…':'Пересчитываем из снимка знаний…');setError('');try{
    const body={constraints,base_plan_id:active?.plan_id,...(repair?{plan:parsedPlan()}:{})}
    const r=await api<Bundle>(`/api/runs/${run.run_id}/${repair?'repair':'replan'}`,body);setProposal(r);setNotice('Вариант готов к сравнению. Активный план пока не изменён. Новых проверок: 0.');setTab('compare')
  }catch(e){setError(String(e))}finally{setBusy('')}}
  async function check(){if(!run)return;setBusy('Проверяем план…');setError('');try{setAudit(await api<Audit>(`/api/runs/${run.run_id}/audit`,{constraints,plan:parsedPlan()}))}catch(e){setError(String(e))}finally{setBusy('')}}
  async function apply(plan:Bundle){if(!run||!active)return;setBusy('Применяем выбранную версию…');setError('');try{const value=await api<Bundle>(`/api/runs/${run.run_id}/apply`,{plan_id:plan.plan_id,expected_active_plan_id:active.plan_id});setScenario(value.plan_id===run.plan_id?null:value);setProposal(null);setSelected(0);setAudit(null);setConstraints({...value.forecast.constraints});setDraft(JSON.stringify(value.plan,null,2));setNotice('Выбранная версия применена. Наблюдения и расходы на проверки сохранены.');setTab('plan')}catch(e){setError(String(e))}finally{setBusy('')}}
  function reset(){if(run)void apply(run)}
  function exportPlan(){if(run&&active)window.location.href=`/api/runs/${run.run_id}/plans/${active.plan_id}/export`}
  async function savePlan(){if(!run||!active)return;try{await api(`/api/runs/${run.run_id}/save`,{plan_id:active.plan_id});setNotice('План сохранён с показателями, ограничениями и основаниями решения.')}catch(e){setError(String(e))}}
  function propose(value:Bundle){setProposal(value);setTab('compare');setAssistantOpen(false)}
  return <div className="app-shell">
    <aside className="nav-rail"><a className="brand" href="/" aria-label="BeeAgent, главная">BeeAgent<span className="brand-dot">.</span></a><div className="powered"><span>powered by Beeline</span><img src="/brand/beeline.svg" alt="Логотип Beeline" width="26" height="26"/></div><div className="workspace-label">AI-агент для управления маркетинговыми кампаниями</div>
      <nav aria-label="Разделы">{[['overview','Обзор'],['plan','Кампании'],['compare','Сравнение'],['audit','Проверки'],['data','Данные']].map(([id,label])=><button key={id} className={tab===id?'nav-item active':'nav-item'} onClick={()=>setTab(id)}><Icon name={id}/>{label}{id==='audit'&&active&&<span className="nav-count">{active.audit.findings.length}</span>}</button>)}</nav>
      <div className="rail-note"><span className="small-label">HACKALEM AI</span><strong>Решения на данных</strong><p>Разработано командой для кейса Beeline на HackAlem AI</p><div className="offline"><i/> Движок работает без интернета</div></div>
    </aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb">Рабочее место аналитика <span>/</span> Тарифные кампании</div><div className="top-actions"><span className="workspace-tag">Демонстрационные данные</span><button className="assistant-trigger" onClick={()=>setAssistantOpen(true)} disabled={!run}><span className="ai-mark">✦</span> AI-ассистент</button></div></header>
      <main><section className="page-heading"><div><div className="eyebrow">BEEAGENT · РЕШЕНИЯ С ОБОСНОВАНИЕМ</div><h1>{tab==='data'?'Данные и наблюдения':tab==='compare'?'Сравнение вариантов':tab==='audit'?'Проверка плана':tab==='plan'?'Кампании':'Кампании с понятной экономикой'}</h1><p>Проверяйте гипотезы, распределяйте бюджет и сравнивайте решения на данных</p></div><div className="launch-controls"><button className="primary" onClick={()=>setLaunchOpen(true)} disabled={!!busy}>Рассчитать план <Icon name="arrow"/></button></div></section>
      {launchOpen&&<section className="panel launch-confirm"><h2>Новый расчёт с проверкой гипотез</h2><p>Агент проведёт до 20 проверок в новом запуске. Они расходуют его бюджет и контакты. Чтобы изменить текущий план на сохранённых наблюдениях, откройте «Изменить условия».</p><details><summary>Параметры проверки</summary><label className="field">Номер прогона<input type="number" min="0" max="4294967295" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label></details><div className="editor-actions"><button className="primary" onClick={research}>Начать расчёт</button><button className="secondary" onClick={()=>setLaunchOpen(false)}>Отмена</button></div></section>}
      {error&&<div role="alert" className="message error">{error.replace('Error: ','')}</div>}{busy&&<div role="status" className="message loading"><span className="spinner"/>{busy}{busy.startsWith('Проверяем гипотезы')&&<button className="text-button" onClick={()=>{polling.current++;setBusy('');setNotice('Ожидание отменено. Запущенные проверки завершатся на сервере; результат появится в сохранённых запусках.');void refresh()}}>Отменить ожидание</button>}</div>}{notice&&!busy&&<div role="status" className="message notice">{notice}</div>}
      {!run&&!busy&&<section className="empty-state"><Icon name="pilot"/><h2>Сначала — наблюдения</h2><p>Рассчитайте первый план. Агент проверит гипотезы на данных кейса и учтёт стоимость каждого контакта.</p><button className="primary" onClick={()=>setLaunchOpen(true)}>Рассчитать план</button></section>}
      {run&&active&&<><div className="run-strip"><span className="source-badge">{scenario?'Изменённый план':'План с проверкой гипотез'}</span><span>Версия {active.plan_id.slice(0,8)}</span><span className="run-time">{new Date(run.created_at).toLocaleString('ru-RU')}</span><select aria-label="Сохранённый запуск" value={run.run_id} onChange={e=>void open(e.target.value)} disabled={!!busy}>{runs.map(r=><option value={r.run_id} key={r.run_id}>{new Date(r.created_at).toLocaleString('ru-RU')} · {r.run_id.slice(0,8)}</option>)}</select></div>
      <section className="metrics" aria-label="Показатели активного плана"><div className="metric main-metric"><div className="small-label">ОЖИДАЕМЫЙ ЧИСТЫЙ ПРИРОСТ</div><strong className={active.forecast.net<0?'negative':''}>{signed(active.forecast.net)}<small>у.е.</small></strong><p>Прогноз модели · может быть завышен</p></div><div className="metric"><div className="small-label">РАСХОД</div><strong>{n(active.forecast.cost)}<small>у.е.</small></strong><p>Включая {n(run.knowledge_summary.spent_budget)} у.е. на проверки</p></div><div className="metric"><div className="small-label">КОНТАКТЫ</div><strong>{n(active.forecast.contacts)}</strong><p>Оценка уникального охвата: {n(active.forecast.estimated_unique)}</p></div><div className="metric"><div className="small-label">КАМПАНИИ</div><strong>{active.plan.length}</strong><p>После {run.pilots.length} проведённых проверок</p></div></section>
      {tab==='overview'&&<><section className="overview-grid"><div className="panel overview-main"><span className="eyebrow">АКТИВНЫЙ ПЛАН</span><h2>У каждого решения есть основания</h2><p>Кампании выбраны с учётом бюджета, порядка контактов и пересечений аудитории. Откройте паспорт, чтобы увидеть наблюдения и неопределённость.</p><div className="overview-actions"><button className="primary" onClick={()=>setTab('plan')}>Открыть кампании <Icon name="arrow"/></button><button className="secondary" onClick={()=>setTab('plan')}>Изменить условия</button></div><div className="overview-campaigns">{active.forecast.details.slice(0,3).map((d,i)=><button key={i} onClick={()=>{setSelected(i);setTab('plan')}}><span className="row-number">{String(i+1).padStart(2,'0')}</span><span><strong>{tariff(d.campaign.filter_current_tariff)} на {tariff(d.campaign.target_tariff)}</strong><small>{channelLabel[d.campaign.channel]} · {n(d.contacts)} контактов</small></span><strong>{signed(d.marginal_net)}</strong></button>)}</div></div><div className="panel measured-panel"><span className="eyebrow">ПРОВЕРКА НА ДАННЫХ КЕЙСА</span><h2>{scenario?'Нет измерения':`${signed(run.official.net_arpu_gain)} у.е.`}</h2><p>{scenario?'Изменённый план ещё не выполнялся в среде. Результат исходного запуска не переносится на него.':'Фактический результат оценщика для этой версии: проверки и финальные кампании вместе.'}</p>{!scenario&&<div className="calibration-gap"><span>Разница прогноза и измерения</span><strong>{signed(active.forecast.net-run.official.net_arpu_gain)} у.е.</strong><p>Прогноз не откалиброван. Нельзя использовать его как обещание дохода.</p></div>}<details><summary>Методика и ограничения</summary><p>Используются синтетические данные кейса. Результаты не отражают показатели Beeline.</p><p>Высокие шумные оценки могут выигрывать отбор. Ожидаемая выручка аудитории усиливает денежную ошибку. Уникальный охват с проверками оценён вероятностно.</p><p>Номер прогона: {run.seed}. Время расчёта: {n(run.seconds,2)} с.</p></details></div></section><div className="action-bar"><button className="secondary" onClick={savePlan}>Сохранить план</button><button className="secondary" onClick={exportPlan}><Icon name="download"/>Экспортировать</button><button className="text-button" onClick={()=>setTab('compare')}>Сравнить варианты</button></div></>}
      {tab==='plan'&&<div className="plan-layout"><div className="plan-main"><section className="panel"><div className="section-title"><div><span className="eyebrow">{scenario?'ИЗМЕНЁННЫЙ ПЛАН':'ИСХОДНЫЙ ПЛАН'}</span><h2>План кампаний <span className="count">{active.plan.length}</span></h2></div><div className="plan-actions"><button className="text-button" onClick={savePlan}>Сохранить план</button><button className="text-button" onClick={exportPlan}><Icon name="download"/>Экспортировать</button></div></div>
          <div className="forecast-band"><div><span>Ожидаемый чистый прирост</span><strong>{signed(active.forecast.net)} <small>у.е.</small></strong></div><div><span>Прогноз расхода</span><strong>{n(active.forecast.cost)}</strong></div><div><span>Контакты</span><strong>{n(active.forecast.contacts)}</strong></div></div>
          {scenario?.delta&&<div className="delta-strip">К базовому прогнозу: <strong>{signed(scenario.delta.net)} у.е.</strong><span>·</span>{signed(scenario.delta.contacts)} контактов<span>·</span>0 новых проверок</div>}
          <div className="table-scroll"><table className="campaign-table"><thead><tr><th>№</th><th>Аудитория и предложение</th><th>Канал</th><th className="number">Контакты</th><th className="number">Чистый вклад</th><th/></tr></thead><tbody>{active.forecast.details.map((d,i)=><tr key={i} className={selected===i?'selected':''}><td><button className="row-number" aria-label={`Паспорт кампании ${i+1}`} onClick={()=>setSelected(i)}>{String(i+1).padStart(2,'0')}</button></td><td><button className="campaign-link" onClick={()=>setSelected(i)}><strong>{tariff(d.campaign.filter_current_tariff)} <span>на</span> {tariff(d.campaign.target_tariff)}</strong><small>{segment(d.campaign.filter_arpu_segment)}{d.campaign.filter_data_segment?` · ${segment(d.campaign.filter_data_segment)}`:''}{d.campaign.filter_call_segment?` · звонки ${segment(d.campaign.filter_call_segment)}`:''}</small></button></td><td><span className={`channel channel-${d.campaign.channel}`}>{channelLabel[d.campaign.channel]}</span></td><td className="number">{n(d.contacts)}{d.truncated&&<small className="warning-text">Усечена</small>}</td><td className={`number ${d.marginal_net<0?'negative':''}`}>{signed(d.marginal_net)}</td><td><button className="icon-button" onClick={()=>setSelected(i)} aria-label={`Открыть доказательства кампании ${i+1}`}><Icon name="arrow"/></button></td></tr>)}</tbody></table></div>
          <div className="table-explanation">Вклад проведённых проверок в прогноз: <strong>{signed(active.forecast.net-active.forecast.details.reduce((sum,d)=>sum+d.marginal_net,0))} у.е.</strong> Вместе с вкладом кампаний выше он составляет прогноз всего плана.</div><div className="table-foot"><span>Порядок определяет усечение и расход.</span><button className="text-button" onClick={()=>setTab('audit')}>Проверить план <Icon name="arrow"/></button></div></section>
          {passport&&<section className="panel passport"><div className="section-title"><div><span className="eyebrow">ПАСПОРТ РЕШЕНИЯ · {String(selected+1).padStart(2,'0')}</span><h2>Почему эта кампания</h2></div><span className={`evidence-status ${passport.status==='Проверено пилотом'?'verified':''}`}>{passport.status==='Проверено пилотом'?'Есть результаты проверки':'Историческая гипотеза'}</span></div><div className="passport-intro"><strong>{tariff(active.plan[selected]?.filter_current_tariff)} на {tariff(active.plan[selected]?.target_tariff)}</strong><p>Проверки: {passport.pilots.length?passport.pilots.map(x=>`№${x}`).join(', '):'для этого направления нет'}. Интервалы отражают статистическую модель; калибровка при сдвиге аудитории не гарантирована.</p></div><div className="evidence-list">{passport.evidence.map(e=><div className="evidence-row" key={e.cell}><div><strong>{tariff(e.cell.split('|')[0])} · {segment(e.cell.split('|')[1])}</strong><span>{n(e.prior.n_history)} переходов в истории · {n(e.samples)} контактов проверок</span></div><div className="interval-value"><strong>{pct(e.channel_mean)}</strong><span>Диапазон модели: {pct(e.interval[0])} … {pct(e.interval[1])}</span></div></div>)}</div>{passport.best_rejected_alternative&&<div className="alternative"><span className="small-label">ЛУЧШАЯ АЛЬТЕРНАТИВА СРЕДИ ЗАМЕН ТАРИФА</span><strong>{tariff(passport.best_rejected_alternative.target)} · {channelLabel[passport.best_rejected_alternative.channel]}</strong><p>Прогноз всего плана при замене: {signed(passport.best_rejected_alternative.plan_net)} у.е. Выбор учитывает неопределённость, порядок и ресурсы.</p></div>}<details><summary>Происхождение оценки и допущения</summary><p>История показывает связь выручки до и после перехода, но не доказывает причинный эффект. Частота переходов — эвристика, не измеренная конверсия. Пилоты обновляют среднее и дисперсию с весом фактического числа контактов.</p><p>SMS, Push и реклама используют общую оценку при допущении, что базовая конверсия лежит от нуля до единицы. Звонки оцениваются отдельно. Пересечения финальных кампаний считаются точно; пилотные — вероятностно, без знания ID.</p><p>{passport.could_change}</p></details><div className="snapshot-label">Снимок {run.knowledge_summary.snapshot_id}</div></section>}
        </div><aside className="scenario-panel"><div className="scenario-heading"><span className="scenario-icon"><Icon name="compare"/></span><div><span className="eyebrow">СОХРАНЁННЫЕ НАБЛЮДЕНИЯ</span><h2>Изменить условия</h2></div></div><p className="scenario-description">Пересчёт на тех же знаниях.<br/>Проверки повторно не запускаются.</p><form onSubmit={e=>{e.preventDefault();void replan()}}><label className="field">Общий бюджет, у.е.<input type="number" min={run.knowledge_summary.spent_budget} step="1" value={constraints.budget} onChange={e=>setConstraints({...constraints,budget:Number(e.target.value)})}/></label><div className="sunk-note">Уже потрачено на проверки: <strong>{n(run.knowledge_summary.spent_budget)} у.е.</strong></div><fieldset><legend>Доступные каналы</legend>{channels.map(ch=><label className="channel-option" key={ch}><input type="checkbox" checked={constraints.channels.includes(ch)} onChange={e=>setConstraints({...constraints,channels:e.target.checked?[...constraints.channels,ch]:constraints.channels.filter(x=>x!==ch)})}/><span>{channelLabel[ch]}</span></label>)}</fieldset><label className="field">Максимум кампаний<select value={constraints.max_campaigns} onChange={e=>setConstraints({...constraints,max_campaigns:Number(e.target.value)})}>{Array.from({length:10},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label><button className="primary full" disabled={!!busy||!constraints.channels.length} type="submit">Сравнить варианты <Icon name="arrow"/></button>{scenario&&<button className="secondary full" type="button" onClick={reset}>Вернуть исходный план</button>}</form><div className="scenario-caution"><strong>Прогноз, не результат оценщика</strong><p>Вариант появится в сравнении. Показатели активного плана изменятся после вашего подтверждения.</p></div><div className="small-label model-label">ЧУВСТВИТЕЛЬНОСТЬ МОДЕЛИ</div><div className="cautious-number">{signed(active.cautious_net)} <small>у.е.</small></div><p className="muted small">Прирост при снижении каждой оценки на одну стандартную ошибку. Это проверка чувствительности, не доверительный интервал всего плана.</p></aside></div>}
      {tab==='data'&&<><section className="panel source-panel"><span className="eyebrow">ИСТОЧНИКИ ДАННЫХ</span><h2>Основания для расчёта</h2><p>Целевая аудитория: {n(run.knowledge_summary.diagnostics.profile_rows)} строк. Исторические переходы и тарифный справочник используются для гипотез; наблюдения проверок обновляют их оценки.</p><div className="source-columns"><div><strong>Профиль аудитории</strong><p>Выручка, тариф и разрешённые сегменты. Порядок контактов задан идентификаторами.</p></div><div><strong>История и тарифы</strong><p>Другая аудитория. Нет контрольной группы и журнала отказов, поэтому это не измеренная конверсия.</p></div><div><strong>Проверки гипотез</strong><p>Фактические контакты, расход и наблюдаемый эффект из публичного интерфейса среды.</p></div></div><p>Используются синтетические данные кейса. Результаты не отражают показатели Beeline.</p><small>Набор наблюдений: {run.data_version}</small></section><section className="panel"><div className="section-title"><div><span className="eyebrow">НАБЛЮДЕНИЯ ПРОВЕРОК</span><h2>{run.pilots.length} шагов исследования</h2></div><span className="source-badge">Сохранённые результаты</span></div><p className="section-description">Ниже сохранены фактические результаты проверок гипотез. Новые условия плана используют эти же наблюдения.</p><div className="table-scroll"><table><thead><tr><th>Шаг</th><th>Гипотеза</th><th>Канал</th><th className="number">Запрос / факт</th><th className="number">Наблюдение</th><th className="number">Расход</th></tr></thead><tbody>{run.pilots.map(p=><tr key={p.index}><td className="muted">{String(p.index).padStart(2,'0')}</td><td><strong>{tariff(p.campaign.filter_current_tariff)} на {tariff(p.campaign.target_tariff)}</strong><small>{segment(p.campaign.filter_arpu_segment)}</small></td><td>{channelLabel[p.campaign.channel]}</td><td className="number">{p.requested_n} / {p.actual_n}</td><td className={`number ${p.observed_ratio<0?'negative':'positive'}`}>{pct(p.observed_ratio)}</td><td className="number">{n(p.cost)}</td></tr>)}</tbody></table></div><div className="data-note"><strong>Качество данных</strong><p>Из групп модели исключено {n(run.knowledge_summary.diagnostics.excluded_missing_or_invalid)} строк с пропущенными или некорректными ключевыми значениями. История относится к другой аудитории. Исходные файлы не изменяются.</p></div></section></>}
      {tab==='compare'&&<>{proposal?<ScenarioComparison base={proposal.base_plan_id===run.plan_id?run:active} proposal={proposal} busy={!!busy} onApply={()=>void apply(proposal)} onReject={()=>{setProposal(null);setNotice('Предложение отклонено. Активный план сохранён.')}}/>:<section className="panel comparison-empty"><h2>Сравните условия перед выбором</h2><p>Измените бюджет, каналы или число кампаний. Новый вариант появится здесь рядом с базовым планом.</p><button className="primary" onClick={()=>setTab('plan')}>Изменить условия</button></section>}<section className="panel"><div className="section-title"><div><span className="eyebrow">ПРОВЕРКА НА ДАННЫХ КЕЙСА · 10 ПРОГОНОВ</span><h2>Сравнение способов выбора</h2></div></div>{comparison?.policies?<><div className="table-scroll"><table><thead><tr><th>Стратегия</th><th className="number">Средний прирост</th><th className="number">Медиана</th><th className="number">Минимум</th><th className="number">В плюс</th><th className="number">Время, с</th></tr></thead><tbody>{comparison.policies.map(p=><tr key={p.policy} className={p.policy==='adaptive'?'highlight-row':''}><td><strong>{policyLabel[p.policy]}</strong></td><td className="number">{signed(p.summary.mean_net)}</td><td className="number">{signed(p.summary.median_net)}</td><td className={`number ${p.summary.min_net<0?'negative':''}`}>{signed(p.summary.min_net)}</td><td className="number">{p.summary.positive_runs} / {p.results.length}</td><td className="number">{n(p.summary.mean_seconds,2)}</td></tr>)}</tbody></table></div><div className="data-note">Разные прогоны проверяют шум наблюдений в одной среде кейса. Это не проверка скрытого судейства и не доказательство устойчивости к другому миру эффектов. Все крайние результаты сохранены в отчёте.</div></>:<p className="section-description">Сравнительная проверка ещё не выполнена. Нет измерения.</p>}</section><section className="panel history-panel"><div className="section-title"><h2>Сохранённые исследования</h2></div><div className="table-scroll"><table><thead><tr><th>Запуск</th><th>Источник</th><th className="number">Измеренный прирост</th><th/></tr></thead><tbody>{runs.map(r=><tr key={r.run_id}><td>Прогон {r.seed}<small>{new Date(r.created_at).toLocaleString('ru-RU')}</small></td><td>Проверка на данных кейса</td><td className="number">{signed(r.official.net_arpu_gain)}</td><td><button className="text-button" onClick={()=>{void open(r.run_id);setTab('plan')}}>Открыть <Icon name="arrow"/></button></td></tr>)}</tbody></table></div></section></>}
      {tab==='audit'&&<div className="audit-layout"><section className="panel"><div className="section-title"><div><span className="eyebrow">КАЧЕСТВО РЕШЕНИЙ</span><h2>Проверить и исправить</h2></div></div><p className="section-description">Редактируйте порядок, фильтры или каналы плана. Проверка обнаружит некорректные значения, пересечения, усечение и неподтверждённые гипотезы. Исправление заново выбирает кампании тем же движком.</p><details className="advanced-plan"><summary>Расширенный редактор плана</summary><label className="editor-label" htmlFor="plan-editor">Правила кампаний · JSON</label><textarea id="plan-editor" className="plan-editor" spellCheck={false} value={draft} onChange={e=>setDraft(e.target.value)}/></details><div className="editor-actions"><button className="secondary" onClick={check} disabled={!!busy}>Проверить план</button><button className="primary" onClick={()=>void replan(true)} disabled={!!busy}>Исправить план <Icon name="arrow"/></button></div></section><section className="panel audit-results"><div className="section-title"><h2>Результат проверки</h2></div>{scenario?.before_audit&&<div className="repair-before">До исправления: {scenario.before_audit.findings.length} замечаний{scenario.before_audit.valid?'':' · есть ошибки'}<br/>После: {scenario.audit.findings.length} замечаний{scenario.audit.valid?' · план валиден':' · есть ошибки'}</div>}<div className={`audit-state ${(audit||active.audit).valid?'ok':'bad'}`}><Icon name="audit"/>{(audit||active.audit).valid?'Правила плана соблюдены':'План требует исправления'}</div>{(audit||active.audit).findings.length===0?<p className="section-description">Проверяемых проблем не обнаружено.</p>:(audit||active.audit).findings.map((f,i)=><div className="finding" key={i}><span className={f.severity==='error'?'finding-marker error-marker':'finding-marker'}/><div><strong>{f.index!==undefined?`Кампания ${f.index+1}`:'Весь план'}</strong><p>{f.message}</p><small>{f.severity==='error'?'Ошибка':'Предупреждение'}</small></div></div>)}<div className="data-note">Валидный план может сохранять предупреждения: например, усечение допустимо по правилам. Оценка неизвестных эффектов не становится точной после проверки.</div></section></div>}
      <footer><span>BeeAgent · powered by Beeline</span><span>Используются синтетические данные кейса. Результаты не отражают показатели Beeline.</span></footer></>}
      </main>
    </div>
    {assistantOpen&&run&&active&&<AssistantPanel runId={run.run_id} original={run} active={active} selected={selected} onClose={()=>setAssistantOpen(false)} onProposal={propose}/>}
  </div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
