import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'

type Campaign = {campaign_name?:string;target_tariff:string;channel:string;filter_current_tariff?:string;filter_arpu_segment?:string;filter_data_segment?:string;filter_call_segment?:string}
type Detail = {campaign:Campaign;audience:number;contacts:number;cost:number;marginal_net:number;uncertainty_scale:number;final_overlap:number;truncated:boolean;campaign_capped:boolean}
type Forecast = {source:string;net:number;gross:number;cost:number;contacts:number;final_unique:number;estimated_unique:number;details:Detail[];constraints:Constraints}
type Constraints = {budget:number;channels:string[];max_campaigns:number;contacts?:number;risk?:number}
type Finding = {code:string;severity:string;message:string;index?:number}
type Audit = {valid:boolean;findings:Finding[];forecast:Forecast}
type Evidence = {cell:string;channel_mean:number;sd:number;interval:number[];samples:number;pilots:number;prior:{n_history:number;historical_change:number;adoption_heuristic:number}}
type Passport = {index:number;status:string;pilots:number[];evidence:Evidence[];best_rejected_alternative:null|{target:string;channel:string;plan_net:number};rejection_reason:string;could_change:string}
type Pilot = {index:number;cell:string;campaign:Campaign;actual_n:number;requested_n:number;cost:number;observed_ratio:number;prior:{mean:number};posterior:{mean:number};reason:string}
type Official = {net_arpu_gain:number;total_cost:number;total_contacts:number;unique_customers_targeted:number;n_pilots:number;status:string}
type Bundle = {plan:Campaign[];forecast:Forecast;audit:Audit;passports:Passport[];cautious_net:number;source:string;new_pilots?:number;delta?:Record<string,number>;before_audit?:Audit}
type Run = Bundle & {run_id:string;seed:number;seconds:number;created_at:string;official:Official;pilots:Pilot[];knowledge_summary:{snapshot_id:string;stop_reason:string;spent_budget:number;spent_contacts:number;diagnostics:{excluded_missing_or_invalid:number;profile_rows:number};assumptions:string[]}}
type RunSummary = Pick<Run,'run_id'|'seed'|'seconds'|'created_at'|'official'|'source'>
type Comparison = {source:string;policies:{policy:string;summary:{mean_net:number;median_net:number;min_net:number;max_net:number;positive_runs:number;mean_seconds:number};results:{seed:number;net_arpu_gain:number}[]}[]}

const n = (x:number|undefined, digits=0) => x == null ? 'Нет оценки' : new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits}).format(x)
const pct = (x:number) => `${n(x*100,1)}%`
const signed = (x:number) => `${x>0?'+':''}${n(x)}`
const tariff = (s:string|undefined) => (s||'Все тарифы').replaceAll('tariff_','T').replaceAll(';',', ')
const channels = ['push','sms','digital_ads','call']
const channelLabel:Record<string,string> = {push:'Push',sms:'SMS',digital_ads:'Реклама',call:'Звонки'}
const policyLabel:Record<string,string> = {template:'Шаблон организаторов',history_only:'Только история',fixed_pilots:'Фиксированные пилоты',adaptive:'LEVRA · адаптивный'}
async function api<T>(url:string, body?:unknown):Promise<T>{
  const response = await fetch(url,body === undefined ? undefined : {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
  const data = await response.json()
  if(!response.ok) throw new Error(data.error || `Ошибка ${response.status}`)
  return data as T
}
function Icon({name}:{name:string}) {const paths:Record<string,React.ReactNode>={plan:<><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></>,pilot:<><path d="M9 3h6M10 3v6L4 19q-1 2 2 2h12q3 0 2-2L14 9V3M8 14h8"/></>,compare:<><path d="M5 20V10M12 20V4M19 20V13"/></>,audit:<><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/></>,arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,download:<><path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{paths[name]||paths.plan}</svg>}
function App(){
  const [runs,setRuns]=useState<RunSummary[]>([]),[run,setRun]=useState<Run|null>(null),[scenario,setScenario]=useState<Bundle|null>(null)
  const [tab,setTab]=useState('plan'),[selected,setSelected]=useState(0),[seed,setSeed]=useState(42),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const [constraints,setConstraints]=useState<Constraints>({budget:100000,channels:[...channels],max_campaigns:10})
  const [draft,setDraft]=useState(''),[audit,setAudit]=useState<Audit|null>(null),[comparison,setComparison]=useState<Comparison|null>(null)
  const active=scenario||run, passport=active?.passports[selected]
  async function refresh(){setRuns(await api<RunSummary[]>('/api/runs'))}
  async function open(id:string){setBusy('Открываем сохранённый запуск…');setError('');try{const r=await api<Run>(`/api/runs/${id}`);setRun(r);setScenario(null);setAudit(null);setSelected(0);setSeed(r.seed);setConstraints({budget:r.forecast.constraints.budget,channels:[...r.forecast.constraints.channels],max_campaigns:10});setDraft(JSON.stringify(r.plan,null,2))}catch(e){setError(String(e))}finally{setBusy('')}}
  useEffect(()=>{api<RunSummary[]>('/api/runs').then(list=>{setRuns(list);if(list[0])void open(list[0].run_id)}).catch(e=>setError(String(e)));api<Comparison>('/api/benchmarks').then(setComparison).catch(()=>{})},[])
  async function research(){setBusy('Выполняется исследование в симуляции…');setError('');setNotice('');try{
    const job=await api<{run_id:string}>('/api/runs',{seed});let completed=false
    for(let attempt=0;attempt<300;attempt++){await new Promise(r=>setTimeout(r,800));const status=await api<{status:string;error?:string}>(`/api/runs/${job.run_id}`);if(status.status==='failed')throw new Error(status.error);if(status.status==='completed'){completed=true;break}}
    if(!completed)throw new Error('Исследование ещё выполняется. Откройте запуск позднее.')
    await refresh();await open(job.run_id);setNotice('Исследование завершено. Показаны сохранённые результаты реального запуска.');setTab('plan')
  }catch(e){setError(String(e))}finally{setBusy('')}}
  async function replan(repair=false){if(!run)return;setBusy(repair?'Исправляем план…':'Пересчитываем из снимка знаний…');setError('');try{
    const body=repair?{constraints,plan:JSON.parse(draft)}:{constraints}
    const r=await api<Bundle>(`/api/runs/${run.run_id}/${repair?'repair':'replan'}`,body);setScenario(r);setSelected(0);setAudit(r.audit);setDraft(JSON.stringify(r.plan,null,2));setNotice(repair?'План исправлен тем же solver. Проверка до и после — ниже.':'Сценарий пересчитан. Новых пилотов: 0.');if(!repair)setTab('plan')
  }catch(e){setError(String(e))}finally{setBusy('')}}
  async function check(){if(!run)return;setBusy('Проверяем план…');setError('');try{setAudit(await api<Audit>(`/api/runs/${run.run_id}/audit`,{constraints,plan:JSON.parse(draft)}))}catch(e){setError(String(e))}finally{setBusy('')}}
  function reset(){if(!run)return;setScenario(null);setSelected(0);setAudit(null);setConstraints({budget:run.forecast.constraints.budget,channels:[...channels],max_campaigns:10});setDraft(JSON.stringify(run.plan,null,2));setNotice('Восстановлен исходный план запуска.')}
  function exportPlan(){if(!active)return;const cols=['campaign_name','filter_arpu_segment','filter_data_segment','filter_call_segment','filter_current_tariff','target_tariff','channel'] as const;const csv=[cols.join(','),...active.plan.map(c=>cols.map(k=>`"${String(c[k]||'').replaceAll('"','""')}"`).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=scenario?'levra_what_if_plan.csv':'levra_run_plan.csv';a.click();URL.revokeObjectURL(url)}
  return <div className="app-shell">
    <aside className="nav-rail"><a className="brand" href="/" aria-label="LEVRA, главная"><span className="brand-symbol">L</span>LEVRA<span className="brand-dot">.</span></a><div className="workspace-label">CAMPAIGN DECISION ENGINE</div>
      <nav aria-label="Разделы">{[['plan','План кампаний'],['pilot','Исследование'],['compare','Сравнение'],['audit','Проверка плана']].map(([id,label])=><button key={id} className={tab===id?'nav-item active':'nav-item'} onClick={()=>setTab(id)}><Icon name={id}/>{label}{id==='audit'&&active&&<span className="nav-count">{active.audit.findings.length}</span>}</button>)}</nav>
      <div className="rail-note"><span className="small-label">СРЕДА</span><strong>HackAlem · Beeline</strong><p>Синтетические данные.<br/>Реальных рассылок нет.</p><div className="offline"><i/> Offline engine</div></div>
    </aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb">Рабочее место аналитика <span>/</span> Тарифные кампании</div><span className="workspace-tag">LOCAL WORKSPACE</span></header>
      <main><section className="page-heading"><div><div className="eyebrow">ИССЛЕДОВАТЬ → ОЦЕНИТЬ → ВЫБРАТЬ</div><h1>{tab==='pilot'?'Журнал исследования':tab==='compare'?'Сравнение стратегий':tab==='audit'?'Проверка плана':'Решения с доказательствами'}</h1><p>От гипотезы к плану кампаний — с учётом цены каждого контакта.</p></div><div className="launch-controls"><label className="seed-label">Seed<input type="number" min="0" max="4294967295" value={seed} onChange={e=>setSeed(Number(e.target.value))} disabled={!!busy}/></label><button className="primary" onClick={research} disabled={!!busy}>Исследовать в симуляции <Icon name="arrow"/></button></div></section>
      {error&&<div role="alert" className="message error">{error.replace('Error: ','')}</div>}{busy&&<div role="status" className="message loading"><span className="spinner"/>{busy}</div>}{notice&&!busy&&<div role="status" className="message notice">{notice}</div>}
      {!run&&!busy&&<section className="empty-state"><Icon name="pilot"/><h2>Сначала — наблюдения</h2><p>Запустите исследование. Агент проверит гипотезы пилотами и рассчитает последовательность кампаний в официальной mock-среде.</p><button className="primary" onClick={research}>Начать исследование</button></section>}
      {run&&active&&<><div className="run-strip"><span className="source-badge">Official mock</span><span>Сохранённый запуск · seed {run.seed}</span><span className="run-time">{n(run.seconds,2)} с · {new Date(run.created_at).toLocaleString('ru-RU')}</span><select aria-label="Сохранённый запуск" value={run.run_id} onChange={e=>void open(e.target.value)} disabled={!!busy}>{runs.map(r=><option value={r.run_id} key={r.run_id}>Seed {r.seed} · {new Date(r.created_at).toLocaleTimeString('ru-RU')} · {signed(r.official.net_arpu_gain)}</option>)}</select></div>
      <section className="metrics" aria-label="Результат официальной mock-оценки"><div className="metric main-metric"><div className="small-label">NET ARPU GAIN <span>Official mock</span></div><strong className={run.official.net_arpu_gain<0?'negative':''}>{signed(run.official.net_arpu_gain)}<small>у.е.</small></strong><p>Результат оценщика · пилоты и финал</p></div><div className="metric"><div className="small-label">РАСХОД</div><strong>{n(run.official.total_cost)}<small>у.е.</small></strong><p>Из {n(run.forecast.constraints.budget)} у.е.</p></div><div className="metric"><div className="small-label">КОНТАКТЫ</div><strong>{n(run.official.total_contacts)}</strong><p>{n(run.official.unique_customers_targeted)} уникальных клиентов</p></div><div className="metric"><div className="small-label">ПРОВЕДЕНО ПИЛОТОВ</div><strong>{n(run.official.n_pilots)}<small>/ 20</small></strong><p>{n(run.knowledge_summary.spent_contacts)} контактов исследования</p></div></section>
      {tab==='plan'&&<div className="plan-layout"><div className="plan-main"><section className="panel"><div className="section-title"><div><span className="eyebrow">{scenario?'СЦЕНАРИЙ · FORECAST/WHAT-IF':'ИСХОДНЫЙ ПЛАН · FORECAST'}</span><h2>План кампаний <span className="count">{active.plan.length}</span></h2></div><button className="text-button" onClick={exportPlan}><Icon name="download"/>CSV</button></div>
          <div className="forecast-band"><div><span>Ожидаемый net</span><strong>{signed(active.forecast.net)} <small>у.е.</small></strong></div><div><span>Прогноз расхода</span><strong>{n(active.forecast.cost)}</strong></div><div><span>Контакты</span><strong>{n(active.forecast.contacts)}</strong></div></div>
          {scenario?.delta&&<div className="delta-strip">К исходному прогнозу: <strong>{signed(scenario.delta.net)} у.е.</strong><span>·</span>{signed(scenario.delta.contacts)} контактов<span>·</span>0 новых пилотов</div>}
          <div className="table-scroll"><table className="campaign-table"><thead><tr><th>№</th><th>Аудитория → тариф</th><th>Канал</th><th className="number">Контакты</th><th className="number">Вклад в net</th><th/></tr></thead><tbody>{active.forecast.details.map((d,i)=><tr key={i} className={selected===i?'selected':''}><td><button className="row-number" aria-label={`Паспорт кампании ${i+1}`} onClick={()=>setSelected(i)}>{String(i+1).padStart(2,'0')}</button></td><td><button className="campaign-link" onClick={()=>setSelected(i)}><strong>{tariff(d.campaign.filter_current_tariff)} <span>→</span> {tariff(d.campaign.target_tariff)}</strong><small>{d.campaign.filter_arpu_segment||'Все ARPU'}{d.campaign.filter_data_segment?` · ${d.campaign.filter_data_segment}`:''}{d.campaign.filter_call_segment?` · звонки ${d.campaign.filter_call_segment}`:''}</small></button></td><td><span className={`channel channel-${d.campaign.channel}`}>{channelLabel[d.campaign.channel]}</span></td><td className="number">{n(d.contacts)}{d.truncated&&<small className="warning-text">Усечена</small>}</td><td className={`number ${d.marginal_net<0?'negative':''}`}>{signed(d.marginal_net)}</td><td><button className="icon-button" onClick={()=>setSelected(i)} aria-label={`Открыть доказательства кампании ${i+1}`}><Icon name="arrow"/></button></td></tr>)}</tbody></table></div>
          <div className="table-foot"><span>Порядок определяет усечение и расход.</span><button className="text-button" onClick={()=>setTab('audit')}>Проверить план <Icon name="arrow"/></button></div></section>
          {passport&&<section className="panel passport"><div className="section-title"><div><span className="eyebrow">DECISION PASSPORT · {String(selected+1).padStart(2,'0')}</span><h2>Почему эта кампания</h2></div><span className={`evidence-status ${passport.status==='Проверено пилотом'?'verified':''}`}>{passport.status}</span></div><div className="passport-intro"><strong>{tariff(active.plan[selected]?.filter_current_tariff)} → {tariff(active.plan[selected]?.target_tariff)}</strong><p>Пилоты: {passport.pilots.length?passport.pilots.map(x=>`№${x}`).join(', '):'для этого направления нет'}. Интервалы отражают статистическую модель; калибровка при сдвиге аудитории не гарантирована.</p></div><div className="evidence-list">{passport.evidence.map(e=><div className="evidence-row" key={e.cell}><div><strong>{tariff(e.cell.split('|')[0])} · {e.cell.split('|')[1]}</strong><span>{n(e.prior.n_history)} исторических переходов · {n(e.samples)} пилотных контактов</span></div><div className="interval-value"><strong>{pct(e.channel_mean)}</strong><span>95%: {pct(e.interval[0])} … {pct(e.interval[1])}</span></div></div>)}</div>{passport.best_rejected_alternative&&<div className="alternative"><span className="small-label">ЛУЧШАЯ АЛЬТЕРНАТИВА СРЕДИ ЗАМЕН ТАРИФА</span><strong>{tariff(passport.best_rejected_alternative.target)} · {channelLabel[passport.best_rejected_alternative.channel]}</strong><p>Net всего плана при замене: {signed(passport.best_rejected_alternative.plan_net)} у.е. Выбор учитывает неопределённость, порядок и ресурсы.</p></div>}<details><summary>Происхождение оценки и допущения</summary><p>История даёт слабую before/after-ассоциацию, а не причинный uplift. Частота переходов — эвристика, не измеренная конверсия. Пилоты обновляют среднее и дисперсию с весом фактического n.</p><p>SMS, push и реклама делят оценку при допущении conversion ∈ [0, 1]. Звонки оцениваются отдельно. Пересечения финальных кампаний считаются точно; пилотные — вероятностно, без знания ID.</p><p>{passport.could_change}</p></details><div className="snapshot-label">Снимок {run.knowledge_summary.snapshot_id}</div></section>}
        </div><aside className="scenario-panel"><div className="scenario-heading"><span className="scenario-icon">↗</span><div><span className="eyebrow">WHAT-IF</span><h2>Изменить условия</h2></div></div><p className="scenario-description">Пересчёт на тех же знаниях.<br/>Пилоты повторно не запускаются.</p><form onSubmit={e=>{e.preventDefault();void replan()}}><label className="field">Общий бюджет, у.е.<input type="number" min={run.knowledge_summary.spent_budget} step="1" value={constraints.budget} onChange={e=>setConstraints({...constraints,budget:Number(e.target.value)})}/></label><div className="sunk-note">Уже потрачено на пилоты: <strong>{n(run.knowledge_summary.spent_budget)} у.е.</strong></div><fieldset><legend>Доступные каналы</legend>{channels.map(ch=><label className="channel-option" key={ch}><input type="checkbox" checked={constraints.channels.includes(ch)} onChange={e=>setConstraints({...constraints,channels:e.target.checked?[...constraints.channels,ch]:constraints.channels.filter(x=>x!==ch)})}/><span>{channelLabel[ch]}</span></label>)}</fieldset><label className="field">Максимум кампаний<select value={constraints.max_campaigns} onChange={e=>setConstraints({...constraints,max_campaigns:Number(e.target.value)})}>{Array.from({length:10},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label><button className="primary full" disabled={!!busy||!constraints.channels.length} type="submit">Пересчитать план <Icon name="arrow"/></button>{scenario&&<button className="secondary full" type="button" onClick={reset}>Вернуть исходный план</button>}</form><div className="scenario-caution"><strong>Прогноз, не результат оценщика</strong><p>Официальные показатели сверху относятся к исходному запуску. Изменённые лимиты используются только в сценарии.</p></div><div className="small-label model-label">ЧУВСТВИТЕЛЬНОСТЬ МОДЕЛИ</div><div className="cautious-number">{signed(active.cautious_net)} <small>у.е.</small></div><p className="muted small">Net при снижении всех оценок на 1σ. Это стресс оценки, не доверительный интервал всего плана.</p></aside></div>}
      {tab==='pilot'&&<section className="panel"><div className="section-title"><div><span className="eyebrow">PUBLIC PILOT OBSERVATIONS</span><h2>{run.pilots.length} шагов исследования</h2></div><span className="source-badge">Replay</span></div><p className="section-description">{run.knowledge_summary.stop_reason}. Ниже сохранены фактические аргументы и результаты каждого пилота.</p><div className="table-scroll"><table><thead><tr><th>Шаг</th><th>Гипотеза</th><th>Канал</th><th className="number">Запрос / факт</th><th className="number">Наблюдение</th><th className="number">Расход</th></tr></thead><tbody>{run.pilots.map(p=><tr key={p.index}><td className="muted">{String(p.index).padStart(2,'0')}</td><td><strong>{tariff(p.campaign.filter_current_tariff)} → {tariff(p.campaign.target_tariff)}</strong><small>{p.campaign.filter_arpu_segment}</small></td><td>{channelLabel[p.campaign.channel]}</td><td className="number">{p.requested_n} / {p.actual_n}</td><td className={`number ${p.observed_ratio<0?'negative':'positive'}`}>{pct(p.observed_ratio)}</td><td className="number">{n(p.cost)}</td></tr>)}</tbody></table></div><div className="data-note"><strong>Качество данных</strong><p>Из базовых клеток исключено {n(run.knowledge_summary.diagnostics.excluded_missing_or_invalid)} строк с пропущенными или некорректными ключевыми значениями. История относится к другой аудитории. Исходные CSV не изменяются.</p></div></section>}
      {tab==='compare'&&<><section className="panel"><div className="section-title"><div><span className="eyebrow">OFFICIAL MOCK · ОДИНАКОВЫЕ SEEDS 0–9</span><h2>Что даёт адаптивное исследование</h2></div></div>{comparison?.policies?<><div className="table-scroll"><table><thead><tr><th>Стратегия</th><th className="number">Средний net</th><th className="number">Медиана</th><th className="number">Худший seed</th><th className="number">В плюс</th><th className="number">Время, с</th></tr></thead><tbody>{comparison.policies.map(p=><tr key={p.policy} className={p.policy==='adaptive'?'highlight-row':''}><td><strong>{policyLabel[p.policy]}</strong></td><td className="number">{signed(p.summary.mean_net)}</td><td className="number">{signed(p.summary.median_net)}</td><td className={`number ${p.summary.min_net<0?'negative':''}`}>{signed(p.summary.min_net)}</td><td className="number">{p.summary.positive_runs} / {p.results.length}</td><td className="number">{n(p.summary.mean_seconds,2)}</td></tr>)}</tbody></table></div><div className="data-note">Разные seed проверяют шум пилотов в одном mock. Это не проверка скрытого судейства и не доказательство устойчивости к другому миру эффектов. Все крайние результаты сохранены в отчёте.</div></>:<p className="section-description">Бенчмарк ещё не выполнен. Показатели появятся после запуска tools/benchmark_levra.py.</p>}</section><section className="panel history-panel"><div className="section-title"><h2>Сохранённые исследования</h2></div><div className="table-scroll"><table><thead><tr><th>Запуск</th><th>Источник</th><th className="number">Net оценщика</th><th/></tr></thead><tbody>{runs.map(r=><tr key={r.run_id}><td>Seed {r.seed}<small>{new Date(r.created_at).toLocaleString('ru-RU')}</small></td><td>Official mock</td><td className="number">{signed(r.official.net_arpu_gain)}</td><td><button className="text-button" onClick={()=>{void open(r.run_id);setTab('plan')}}>Открыть <Icon name="arrow"/></button></td></tr>)}</tbody></table></div></section></>}
      {tab==='audit'&&<div className="audit-layout"><section className="panel"><div className="section-title"><div><span className="eyebrow">PLAN AUDIT & REPAIR</span><h2>Проверить и исправить</h2></div></div><p className="section-description">Редактируйте порядок, фильтры или каналы плана. Проверка обнаружит некорректные значения, пересечения, усечение и неподтверждённые гипотезы. Исправление заново выбирает кампании тем же solver.</p><label className="editor-label" htmlFor="plan-editor">План кампаний · JSON</label><textarea id="plan-editor" className="plan-editor" spellCheck={false} value={draft} onChange={e=>setDraft(e.target.value)}/><div className="editor-actions"><button className="secondary" onClick={check} disabled={!!busy}>Проверить план</button><button className="primary" onClick={()=>void replan(true)} disabled={!!busy}>Исправить автоматически <Icon name="arrow"/></button></div></section><section className="panel audit-results"><div className="section-title"><h2>Результат проверки</h2></div>{scenario?.before_audit&&<div className="repair-before">До исправления: {scenario.before_audit.findings.length} замечаний{scenario.before_audit.valid?'':' · есть ошибки'}<br/>После: {scenario.audit.findings.length} замечаний{scenario.audit.valid?' · план валиден':' · есть ошибки'}</div>}<div className={`audit-state ${(audit||active.audit).valid?'ok':'bad'}`}><Icon name="audit"/>{(audit||active.audit).valid?'Контракт соблюдён':'План требует исправления'}</div>{(audit||active.audit).findings.length===0?<p className="section-description">Проверяемых проблем не обнаружено.</p>:(audit||active.audit).findings.map((f,i)=><div className="finding" key={i}><span className={f.severity==='error'?'finding-marker error-marker':'finding-marker'}/><div><strong>{f.index!==undefined?`Кампания ${f.index+1}`:'Весь план'}</strong><p>{f.message}</p><small>{f.severity==='error'?'Ошибка':'Предупреждение'} · {f.code}</small></div></div>)}<div className="data-note">Валидный план может сохранять предупреждения: например, усечение допустимо по правилам. Оценка неизвестных эффектов не становится точной после проверки.</div></section></div>}
      <footer><span>LEVRA · Campaign Decision Engine</span><span>Forecast ≠ Official mock ≠ скрытое судейство</span></footer></>}
      </main>
    </div>
  </div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
