import { createContext, useContext } from 'react'
import type { Campaign, Pilot, Bundle } from './main'
export type TariffRow={tariff_plan_code:string;price_tariff:number;Data_in_PKG:number;Min_another_operator_in_PKG:number;Min_another_operator_and_city_in_PKG:number}
export const TariffContext=createContext<TariffRow[]>([])
export const number=(value:number,digits=0)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits}).format(value)
export const tariffName=(code?:string)=>code?'Тариф '+code.replace('tariff_',''):'Все тарифы'
export const channelLabel:Record<string,string>={push:'Push',sms:'SMS',digital_ads:'Реклама',call:'Звонки'}
export const evidenceLabel:Record<string,string>={strong:'Сильные основания',moderate:'Умеренные основания',limited:'Ограниченные основания'}
export function packageText(t:TariffRow){return [number(t.price_tariff,1)+' у.е./мес',...(t.Data_in_PKG?[number(t.Data_in_PKG/1024,2)+' ГБ']:[]),...(t.Min_another_operator_in_PKG?[number(t.Min_another_operator_in_PKG)+' мин на других операторов']:[]),...(t.Min_another_operator_and_city_in_PKG?[number(t.Min_another_operator_and_city_in_PKG)+' мин на операторов и городские']:[])].join(' · ')}
export function Tariff({code,compact=false}:{code?:string;compact?:boolean}){const catalog=useContext(TariffContext);const codes=code?.split(';').filter(Boolean)||[];if(codes.length>1)return <details className="tariff-list"><summary>Текущие тарифы: {codes.length}</summary>{codes.map(c=><Tariff key={c} code={c}/>)}</details>;const row=catalog.find(t=>t.tariff_plan_code===code);return <span className="tariff" title={code}><strong>{tariffName(code)}</strong>{row&&!compact&&<small>{packageText(row)}</small>}</span>}
const group=(c:string)=>c==='call'?'call':'linear'
function contains(c:Campaign,p:Pilot){return c.target_tariff===p.campaign.target_tariff&&group(c.channel)===group(p.campaign.channel)&&(!c.filter_current_tariff||c.filter_current_tariff.split(';').includes(p.campaign.filter_current_tariff||''))&&(!c.filter_arpu_segment||c.filter_arpu_segment===p.campaign.filter_arpu_segment)}
export function pilotConsequence(p:Pilot){const d=p.decision_change;if(!d)return 'Изменение плана не записано в этом архивном запуске.';const before=d.before.plan.findIndex(c=>contains(c,p)),after=d.after.plan.findIndex(c=>contains(c,p));if(before>=0&&after<0)return 'Направление исключено из предварительного плана.';if(before<0&&after>=0)return 'Направление добавлено в план на позицию '+(after+1)+'.';if(before>=0&&after<before)return 'Приоритет повышен: позиция '+(before+1)+' сменилась на '+(after+1)+'.';if(before>=0&&after>before)return 'Сохранено в плане: позиция '+(before+1)+' сменилась на '+(after+1)+'.';if(before>=0)return 'Сохранено в плане на позиции '+(after+1)+'.';if(d.selection_changed){const removed=d.before.plan.filter(c=>!d.after.plan.some(a=>identity(a)===identity(c))).length,added=d.after.plan.filter(c=>!d.before.plan.some(a=>identity(a)===identity(c))).length;return 'Направление осталось вне плана. Убрано кампаний: '+removed+', добавлено: '+added+'; учтён расход пилота.'}return 'Решение не изменилось: направление осталось вне плана.'}
const audience=(c:Campaign)=>[c.filter_current_tariff,c.filter_arpu_segment,c.filter_data_segment,c.filter_call_segment].map(x=>x||'').join('|')
const identity=(c:Campaign)=>[audience(c),c.target_tariff,c.channel].join('|')
export function campaignChanges(base:Bundle,proposed:Bundle){const used=new Set<number>();const rows:{kind:string;before?:number;after?:number}[]=[];base.plan.forEach((c,i)=>{let j=proposed.plan.findIndex((p,k)=>!used.has(k)&&identity(p)===identity(c));if(j<0)j=proposed.plan.findIndex((p,k)=>!used.has(k)&&audience(p)===audience(c));if(j<0){rows.push({kind:'Убрана',before:i});return}used.add(j);const a=base.forecast.details[i],b=proposed.forecast.details[j];if(identity(c)!==identity(proposed.plan[j])||i!==j||a.contacts!==b.contacts||a.cost!==b.cost||a.marginal_net!==b.marginal_net)rows.push({kind:'Изменена',before:i,after:j})});proposed.plan.forEach((_,j)=>{if(!used.has(j))rows.push({kind:'Добавлена',after:j})});return rows}
