import type { Bundle } from './main'
import {campaignChanges, Tariff, channelLabel} from './presentation'
const n=(x:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(x)
const labels:Record<string,string>={push:'Push',sms:'SMS',digital_ads:'Реклама',call:'Звонки'}
export function ScenarioComparison({base,proposal,busy,onApply,onReject}:{base:Bundle;proposal:Bundle;busy:boolean;onApply:()=>void;onReject:()=>void}){
  const changes=campaignChanges(base,proposal)
  const rows:[string,string,string][]=[['Лимит бюджета',n(base.forecast.constraints.budget),n(proposal.forecast.constraints.budget)],['Каналы',base.forecast.constraints.channels.map(x=>labels[x]).join(', '),proposal.forecast.constraints.channels.map(x=>labels[x]).join(', ')],['Кампании',String(base.plan.length),String(proposal.plan.length)],['Расход, у.е.',n(base.forecast.cost),n(proposal.forecast.cost)],['Контакты',n(base.forecast.contacts),n(proposal.forecast.contacts)],['Оценка уникального охвата',n(base.forecast.estimated_unique),n(proposal.forecast.estimated_unique)],['Расчётный прогноз, у.е.',n(base.forecast.net),n(proposal.forecast.net)]]
  return <section className="panel proposal-panel"><div className="section-title"><div><span className="eyebrow">Предложение ожидает вашего решения</span><h2>Что изменится в плане</h2></div><span className="source-badge">Без новых проверок</span></div><div className="table-scroll"><table><thead><tr><th>Показатель</th><th>Базовый план</th><th>Предложенный вариант</th></tr></thead><tbody>{rows.map(([label,b,p])=><tr key={label}><td>{label}</td><td>{b}</td><td className={b!==p?'changed-value':''}>{p}</td></tr>)}</tbody></table></div><section className="campaign-diff"><h3>Изменения кампаний</h3><p>{changes.filter(c=>c.kind==='Добавлена').length} добавлено · {changes.filter(c=>c.kind==='Убрана').length} убрано · {changes.filter(c=>c.kind==='Изменена').length} изменено</p>{changes.map((c,i)=><details key={i}><summary>{c.kind}: {c.before!=null?'кампания '+(c.before+1):'новая кампания '+((c.after||0)+1)}</summary><div className="decision-pair">{([['Было',base,c.before],['Предложено',proposal,c.after]] as const).map(([label,bundle,index])=>{if(index==null)return <div key={label}>{label}: нет в плане</div>;const d=bundle.forecast.details[index];return <div key={label}><strong>{label} · позиция {index+1}</strong><p>Текущий: <Tariff code={d.campaign.filter_current_tariff}/></p><p>Рекомендация: <Tariff code={d.campaign.target_tariff}/></p><p>{channelLabel[d.campaign.channel]} · {n(d.contacts)} контактов · {n(d.cost)} у.е.</p><p>Модельный вклад: {n(d.marginal_net)} у.е.</p></div>})}</div></details>)}</section><div className="data-note"><strong>Основания изменения</strong><p>Движок заново выбрал последовательность кампаний при новых ограничениях. Расходы на уже проведённые проверки сохранены. Измеренного результата нового варианта пока нет.</p><details><summary>Подробности версий</summary><p>Базовая версия: {base.plan_id.slice(0,8)}. Вариант: {proposal.plan_id.slice(0,8)}. Набор наблюдений: {proposal.data_version}.</p></details>{proposal.before_audit&&<p>Ошибки до исправления: {proposal.before_audit.findings.filter(f=>f.severity==='error').length}. После: {proposal.audit.findings.filter(f=>f.severity==='error').length}. Предупреждений осталось: {proposal.audit.findings.filter(f=>f.severity!=='error').length}.</p>}</div><div className="proposal-actions"><button className="primary" disabled={busy} onClick={onApply}>Применить этот вариант</button><button className="secondary" disabled={busy} onClick={onReject}>Оставить текущий план</button></div></section>
}
